#!/usr/bin/env escript
%%! -sname export_residents
%%
%% Export the archived phase 0 champions into the resident field this service
%% ships with.
%%
%% THIS EXISTS SO A VISITOR HAS SOMETHING WORTH FIGHTING. Without it the service
%% would ship with scripted bots only, and a visitor's result would say nothing
%% about how it fares against a trained network.
%%
%% ONE-TIME AND REPRODUCIBLE. It reads the champion archive of a RESEARCH repo,
%% which this service does not and must not depend on at runtime. The output is
%% checked in; this script exists so the provenance of that file is a command
%% rather than a story.
%%
%% GENOMES ARE STORED AS {Layers, Weights}, NOT AS PACKED BYTES, deliberately.
%% Packed bytes would be opaque in a diff and would freeze a wire-format version
%% into a data file. Storing the pair keeps the file readable, lets the service
%% pack and VALIDATE every resident at boot against whatever the current format
%% is, and means a resident's content id is always computed rather than stored,
%% so it can never go stale against the genome it names.
%%
%% Usage:
%%   scripts/export_residents.escript <champion-archive-dir> <out-file>

main([Dir, Out]) ->
    Files = [{s, "exp066_champions_s.eterm"},
             {l, "exp066_champions_l.eterm"},
             {d, "exp066_champions_d.eterm"}],
    Residents = lists:append([read_arm(Dir, Arm, F) || {Arm, F} <- Files]),
    ok = write(Out, Residents),
    io:format("~p residents written to ~s~n", [length(Residents), Out]),
    summarise(Residents);
main(_Args) ->
    io:format("usage: export_residents.escript <champion-archive-dir> <out-file>~n"),
    halt(1).

read_arm(Dir, Arm, File) ->
    Path = filename:join(Dir, File),
    read_terms(Arm, Path, file:consult(Path)).

read_terms(Arm, Path, {ok, Terms}) ->
    io:format("~s: ~p champions~n", [Path, length(Terms)]),
    [resident(Arm, T) || T <- Terms];
read_terms(_Arm, Path, {error, Why}) ->
    io:format("SKIPPED ~s (~p)~n", [Path, Why]),
    [].

%% The archive's own shape, {champion, Arm, Seed, Layers, Weights, Fitness,
%% Budget}. Matched positionally and strictly: a change to the archive format
%% should stop this script rather than silently export something else.
resident(Arm, {champion, Arm, Seed, Layers, Weights, Fitness, Budget}) ->
    #{arm => Arm,
      seed => Seed,
      layers => Layers,
      weights => Weights,
      train_fitness => Fitness,
      budget => Budget}.

write(Out, Residents) ->
    Header =
        "%% THE RESIDENT FIELD. Generated by scripts/export_residents.escript.\n"
        "%%\n"
        "%% Do not hand-edit. Every entry is a champion evolved during Robo Rumble\n"
        "%% phase 0 and archived with the experiment that produced it. `arm' and\n"
        "%% `seed' are its provenance there, and they are carried onto the wire so a\n"
        "%% published result can be traced back to the run that made the opponent.\n"
        "%%\n"
        "%% THE FIELD IS NOT A NEUTRAL SAMPLE AND MUST NOT BE READ AS ONE. Arm s is\n"
        "%% 20 seeds of one optimiser on one topology; arm l has no hidden layer at\n"
        "%% all; arm d was trained against a SINGLE opponent rather than the full\n"
        "%% ladder, and 8 of its 10 lose to a rung below the one they trained on.\n"
        "%% They are a real and diverse field to fight, and they are not a random\n"
        "%% draw from the space of tanks.\n"
        "%%\n"
        "%% Richer per-champion provenance (held-out win rates, behavioural regime,\n"
        "%% cross-play row means for arm s) lives with the experiment, in\n"
        "%% faber-programmes/programmes/p7_coevolution/exp066_competence_floor/.\n\n",
    Body = [io_lib:format("~p.~n", [R]) || R <- Residents],
    file:write_file(Out, [Header | Body]).

summarise(Residents) ->
    Arms = lists:usort([maps:get(arm, R) || R <- Residents]),
    [io:format("  arm ~p: ~p residents, topologies ~p~n",
               [A,
                length([R || R <- Residents, maps:get(arm, R) =:= A]),
                lists:usort([maps:get(layers, R) || R <- Residents,
                                                   maps:get(arm, R) =:= A])])
     || A <- Arms],
    ok.
